blog/urls.py
# blog/urls.py
"""This is the url route for blog app"""
from django.urls import path

from blog import views

app_name='blog'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('post/', views.PostListView.as_view(), name='post_list'),
    path('post/<slug:slug>/<int:year>/<int:month>/<int:day>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/update/<slug:slug>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('post/delete/<slug:slug>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('post/tag/<slug:tag_slug>/', views.PostByTagListView.as_view(), name='post_list_by_tag'),  # calling list view using tag
    # path('post/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),
    ]+ urlpatterns

blog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db.models import Q
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.db import models
from autoslug import AutoSlugField
from taggit.managers import TaggableManager


class PublishedManger(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='pb')


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField('Current Age', blank=True, null=True)


class Post(models.Model):
    class StatusChoice(models.TextChoices):
        published = 'pb', _('Published')
        draft = 'df', _('Draft')

    # STATUS_CHOICES = (
    #     ('draft', 'Draft'),
    #     ('published', 'Published'),
    # )
    title = models.CharField("Title of the post", max_length=50)
    tags = TaggableManager()
    total_views = models.IntegerField(default=0, blank=True, null=True)
    body = models.TextField("Post Content")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # or get_user_model()
    publish = models.DateTimeField("Publish Date", default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = AutoSlugField(populate_from='title', unique_with=['title'], editable=False)
    # status = models.CharField(choices=STATUS_CHOICES, default='draft')
    status = models.CharField(max_length=10, choices=StatusChoice.choices, default=StatusChoice.draft)
    objects = models.Manager()
    # objects = PublishedManger()
    published = PublishedManger()

    def __str__(self):
        return self.title

    def get_hits(self):     # we can achieve this using sessions too
        self.total_views += 1
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.slug,
                             self.publish.strftime('%Y'),
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             ])

    """If i use kwargs={'slug_post'} then i have to specify in views of detail view slug_kwargs_url ='slug_post'"""

    class Meta:
        # Entry.objects.latest('pub_date') in view we can use like this
        ordering = ('-publish',)
        # get_latest_by = "created"


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='User')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    body = models.TextField('Comments')
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.body

blog/forms.py
# blog/forms.py
from blog.models import CustomUser, Comment
from django import forms


class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'age', 'password')


class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=25)
    email = forms.EmailField(label='Email Address')
    contact_number = forms.IntegerField(label='Contact Number', required=False)
    location = forms.CharField(max_length=20, required=False)
    short_message = forms.CharField(label='Message', max_length=100, required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('post', 'body',)
        
# this is how meta class works        
# base_fields = {
# 'name': forms.CharField(max_length=50),
# 'age': forms.IntegerField(default=0),
# 'bio': forms.CharField(max_length=100, widgets=Textarea),
# } 

# ContactForm = type('ContactForm', (forms.BaseForm),{'base_fields':base_fields},)

blog/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, FormView
from django.views.generic.edit import FormMixin, UpdateView, DeleteView, ModelFormMixin
from taggit.models import Tag, TaggedItem

from blog.forms import ContactForm, CommentForm
from blog.models import Post, Comment


class HomePageView(TemplateView):
    template_name = 'blog/home.html'


class AboutPageView(TemplateView):
    template_name = 'blog/about.html'


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    """This limits the number of objects per page and adds a paginator and page_obj to the context. 
    To allow your users to navigate between pages, add links to the next and previous page, in your 
    template like this:"""
    paginate_by = 5
    # queryset = Post.objects.all()
    context_object_name = 'post_list'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Post.published.filter(Q(title__icontains=query) | Q(author__username__icontains=query))
        return Post.published.all()


class PostDetailView(FormMixin, DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["similar_posts"] = self.object.tags.similar_objects()[:4]
        return context

    def dispatch(self, request, *args, **kwargs):
        self.get_object().get_hits()
        return super().dispatch(request, *args, **kwargs)


class PostCreateView(CreateView):
    model = Post
    template_name = 'blog/post_create.html'
    fields = ('title', 'tags', 'body', 'publish', 'status')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'blog/contact.html'
    success_url = '/'


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_update.html'
    fields = ('title', 'tags', 'body', 'publish', 'status')


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('blog:post_list')


class PostByTagListView(ListView):
    model = Post
    template_name = 'blog/post_list_by_tag.html'
    context_object_name = 'post_list'
    paginate_by = 5

    def get_queryset(self):
        query = self.kwargs['tag_slug'] # get_object_or_404(Tag, slug = tag_slug)
        # return queryset.filter(tags__in=[p])
        return get_list_or_404(Post, tags__slug=query)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['tag_name'] = self.kwargs['tag_slug']
        return context

blog/templates/blog/about.html
<!--blog/about-->
{% extends '_base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}About{% endblock title %}</title>
</head>
<body>
{% block content %}
<h2>About</h2>
<p> This is the about section of this page.</p>
{% endblock content %}
</body>
</html>

blog/templates/blog/contact.html
<!--blog/contact.htnl-->
{% extends '_base.html' %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Contact{% endblock title %}</title>
</head>
<body>
{% block content %}
<h3> Contact Details </h3>
<div class="card mt-3 hover-shadow" itemscope="" itemtype="">
    <div class="card-body">
        <h5> Blog World </h5>
        <p>Location: Oberhausen, Germany </p>
        <p>Contact Number: +97152556003697 </p>
        <p>CEO/CTO: Dikshant Ghimire </p>
    </div>
</div>
<h3>Contact Form</h3>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Send">
</form>

{% endblock content %}
</body>
</html>

blog/templates/blog/home.html
<!--blog/home-->
{% extends '_base.html' %}
{% load blog_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock title %}</title>
</head>
<body>
{% block content %}
Welcome to my home page. There are currently {% total_posts %} posts.
<div class='container'>
    <hr>
<h3>Most Commented posts:</h3>
    {%	most_commented_posts	as	most_commented_post	%}
{% for post in most_commented_post %}
    <ul>
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
</ul>
        {% endfor %}

</div>
{% endblock content %}
</body>
</html>

blog/templates/blog/pagination.html
<!--blog/pagination.html-->
<div	class="pagination">
		<span	class="step-links">
            {%	if	page_obj.has_previous or page_obj.has_next %}
                <span	class="current">
                    Showing	page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}<br>
                </span>
            {% endif %}
            {%	if	page_obj.has_previous	%}
                <a	href="?page={{	page_obj.previous_page_number }}">Previous</a>
			{%	endif	%}

            {%	if	page_obj.has_next	%}
                <a href="?page={{ page_obj.next_page_number }}">Next</a>
            {%	endif	%}
		</span>
</div>

blog/templates/blog/post_comment.html
<!--blog/post_comment.html-->
{% load humanize %}
{% load crispy_forms_tags %}
<!--display comment-->
<p>{{post.comments.all|length}} comment{{post.comments.all|pluralize }}</p>
{% for comment in post.comments.all %}
<div class="card mt-2 hover-shadow" itemscope="" itemtype="">
    <div class="card-body">
        <small>{{ comment.author|title}} | {{ comment.created }} ({{ comment.created|naturaltime }})</small>
        <p>{{ comment.body}}</p>
    </div>
</div>
{% endfor %}
<br>
<!--add a new comment-->
<div class="container">
    <h5>Add New Comment</h5>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Comment">
    </form>
</div>

blog/templates/blog/post_create.html
<!--blog/post_create.html-->
{% extends '_base.html' %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}New post creation{% endblock title %}</title>
</head>
<body>
{% block content %}
<h2>Create a New Post</h2><hr>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Create">
</form>
{% endblock content %}
</body>
</html>

blog/templates/blog/post_delete.html
<!--blog/post_delete.html-->
{% extends '_base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Post Delete{% endblock title %}</title>
</head>
<body>
{% block content %}
<h3> Delete Page!!</h3>
<p>Are you sure you want to delete {{ post.title }}?? </p>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete">
    <input type="reset" value="No">

</form>
{% endblock content %}
</body>
</html>

blog/templates/blog/post_detail.html
<!--blog/post_detail.html-->
{% extends '_base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ post}}{% endblock title %}</title>
</head>
<body>
{% block content %}
<h2>{{ post.title|title }}</h2> <hr>
<div class="blockquote-footer"> Author : {{ post.author|title }} | Published Date : {{ post.publish }}|
    Total views: {{ object.total_views }} | Tags:
    {% for tag in post.tags.all %}
    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag }} </a>
    {% endfor %}
    |
    <a href="{% url 'blog:post_update' post.slug %}">
        Edit</a> | <a href="{% url 'blog:post_delete' post.slug %}">Delete</a> </div>
<!--post.publish|date:'Y'-->
<!--this join is equivalent to ", ".join(posts.tags.all)-->
<div>
    <p>{{ post.body|linebreaks }}</p>
</div>
<!--similar posts-->
<h3>Similar posts</h3>
{% for posts in similar_posts %}
<ul>
<li><a href="{{ posts.get_absolute_url }}">{{ posts.title}}</a></li>
</ul>
    {% endfor %}

<h3>Comments</h3>
<hr>
{% include 'blog/post_comment.html' %}
{% endblock content %}
</body>
</html>

blog/templates/blog/post_list.html
<!--blog/post_list.html-->
{% extends '_base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Post List| Search{% endblock title %}</title>
</head>
<body>
{% block content %}
{% include 'blog/search_post.html' %} <a href="{% url 'blog:post_create' %}">Create New Post</a> | Total posts found : {{ page_obj.paginator.count }}
{% for post in post_list %}
<div class="card mt-3 hover-shadow" itemscope="" itemtype="">
    <div class="card-body">
        <h5> <a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a> </h5>
        <p class="font-italic text-secondary"> <small>Author: {{ post.author }}</small></p>
        <p>{{ post.body|truncatewords:20 }}</p>
    </div>
</div>
{% endfor %}
{%	include	"blog/pagination.html" %}
{% endblock content %}
</body>
</html>

blog/templates/blog/post_list_by_tag.html
<!--blog/post_list_by_tag.html-->
{% extends '_base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}List by tag {% endblock title %}</title>
</head>
<body>
{% block content %}
Found total posts by tag "{{ tag_name }}" : {{ page_obj.paginator.count }}
{% for post in post_list %}
<div class="card mt-3 hover-shadow" itemscope="" itemtype="">
    <div class="card-body">
        <h5> <a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a> </h5>
        <p class="font-italic text-secondary"> <small>Author: {{ post.author }}</small></p>
        <p>{{ post.body|truncatewords:20 }}</p>
    </div>
</div>
{% endfor %}
{%	include	"blog/pagination.html" %}
{% endblock content %}
</body>
</html>

blog/templates/blog/post_update.html
<!--blog/post_update.html-->
{% extends '_base.html' %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Form Update{% endblock title %}</title>
</head>
<body>
{% block content %}
<h2>Update the Post</h2><hr>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update">
</form>
{% endblock content %}
</body>
</html>

blog/templates/blog/search_post.html
<!--blog/search_post.html-->
<!--Search-->
<form class="form-inline mt-2 mt-md-0" action="{% url 'blog:post_list' %}" method="get">
    <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search using title or author" aria-label="Search">
    <button type="submit" class="btn btn-success text-white">SEARCH POSTS</button>
</form>

templates/_base.html
<!--templates/_base.html-->
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <!--    css-->
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% endblock css %}

</head>
    <header>
        <!-- Fixed navbar -->
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <a class="navbar-brand my-0 mr-md-auto font-weight-normal" href="{% url 'blog:homepage' %}">Blog World</a>
            <nav class="my-2 my-md-0 mr-md-3">
                <a class="p-2 text-dark" href="{% url 'blog:contact' %}">Contact</a>
                <a class="p-2 text-dark" href="{% url 'blog:about' %}">About</a>
                <a class="p-2 text-dark" href="{% url 'blog:post_list' %}">Blogs</a>
                    {% if user.is_authenticated %}
                        <a class="p-2 text-dark" href="{% url 'account_logout' %}">Log Out</a> |
                        <strong class="p-2 text-dark">Hi {{ user.username }}, Welcome </strong>
                    {% else %}
                        <a class="p-2 text-dark" href="{% url 'account_login' %}">Log In</a>
                        <a class="btn btn-outline-primary" href="{% url 'account_signup' %}">Sign Up</a>
                    {% endif %}
            </nav>
        </div>
    </header>
<body>
<div class="container">
{% block content %}

{% endblock content %}
</div>
</body>
<!--jss-->
{% block script %}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock script %}
</html>